from enum import Enum
import argparse
import os
import re

#TODO: add more codes if needed
class ReturnCodes(Enum):
    SUCCESS = 0
    ERROR = -1
    NO_ARGS_GIVEN = -2
    INVALID_ARGS = -3
    INVALID_INPUT_FILE = -4
    INVALID_INPUT_FILE_FORMAT = -5
    MISSING_INPUT_FILE = -6
    INVALID_INPUT_FILE_PATH = -7

def createCompileParser(pParser: argparse.ArgumentParser | None = None, isStandalone: bool = False) -> argparse.ArgumentParser | None:
    parser: argparse.ArgumentParser = pParser
    if isStandalone or parser is None:
        ...
    compileGroup = parser.add_argument_group("Compile specific Commands", description="Options that are specific for compiling")
    compileGroup.add_argument(
                        "-i", "--InputFile",
                        dest="inputFile",
                        help="The path of the input file to process. Must be a .csv file (Mandatory)",
                        required=True
                        )
    compileGroup.add_argument(
                        "-o", "--OutputFile",
                        dest="outputFile",
                        help="The path of the output file. If not set, the name of the input file will be used instead"
                        )
    ...

def createMergeParser(pParser: argparse.ArgumentParser | None = None, isStandalone: bool = False) -> argparse.ArgumentParser | None:
    parser: argparse.ArgumentParser = pParser
    if isStandalone or parser is None:
        ...
    mergeGroup = parser.add_argument_group("Merge specific Commands", description="Options that are specific for merging")
    mergeGroup.add_argument(
                        "-o", "--OldFile",
                        dest="oldFile",
                        help="The path of the input file of the old data to merge. Must be a .xlsx file (Mandatory)",
                        required=True
                        )
    mergeGroup.add_argument(
                        "-n", "--NewFile",
                        dest="newFile",
                        help="The path of the input file of the new data to merge. Must be a .xlsx file (Mandatory)",
                        required=True
                        )
    mergeGroup.add_argument(
                        "-m", "--MergedFile",
                        dest="mergedFile",
                        help="""The path of the output file. If not set, the name will be generated by this pattern: 
    '[old file name (with path)]-[new file name (without path)]_merged.xlsx'"""
                        )
    mergeGroup.add_argument(
                        "-c", "--CompileCSV",
                        dest="compileCSV",
                        action="store_true",
                        help="[Not yet implemented] Try to automatically compile .csv files if given as input"
                        )
    ...

def extractCommonArgs(pArgs: dict | argparse.Namespace | None = None) -> dict | None:
    """Return dictionary structure:
    {
        "ReturnCode": (ReturnCode),
        "args": {
            (Argname): (Value or ReturnCode)        
        },
        "errorMessages": { (if needed)
            (Argname): (Error message)
        }    
    }
    """
    args = vars(pArgs)
    result: dict = {
        "ReturnCode": ReturnCodes.SUCCESS,
        "args": {

        },
        "errorMessages": {

        }
    }

    if args["wantedOS"] is None:
        result["args"]["wantedOS"] = "Windows"
    else:
        result["args"]["wantedOS"] = args["wantedOS"]
    result["args"]["deviceLinkSkip"] = args["deviceLinkSkip"]
    result["args"]["emailLinks"] = args["emailLinks"]
    result["args"]["keepDeviceIds"] = args["keepDeviceIds"]

    print(result)
    return result

# extract the needed arguments into a dict to be given to the actual module and check if they are valid
def extractCompileArgs(pArgs: argparse.Namespace | None = None) -> dict | None:
    """Return dictionary structure:
    {
        "ReturnCode": (ReturnCode),
        "args": {
            (Argname): (Value or ReturnCode)        
        },
        "errorMessages": { (if needed)
            (Argname): (Error message)
        }    
    }
    """
    args = vars(pArgs)
    if pArgs is None:
        result["ReturnCode"] = ReturnCodes.NO_ARGS_GIVEN
        return result
    result = extractCommonArgs(pArgs)

    if args["inputFile"] == None:
        result["ReturnCode"] = ReturnCodes.ERROR
        result["args"]["inputFile"] = ReturnCodes.MISSING_INPUT_FILE
        result["errorMessages"]["inputFile"] = "Error, no input file given!"
    elif not os.path.exists(args["inputFile"]):
        result["ReturnCode"] = ReturnCodes.ERROR
        result["args"]["inputFile"] = ReturnCodes.INVALID_INPUT_FILE_PATH
        result["errorMessages"]["inputFile"] = "Given input file does not exist!"
    elif not str(args["inputFile"]).endswith(".csv"):
        result["ReturnCode"] = ReturnCodes.ERROR
        result["args"]["inputFile"] = ReturnCodes.INVALID_INPUT_FILE_FORMAT
        result["errorMessages"]["inputFile"] = "Error, given input file is possibly not correct file type!\nPlease give a file with the '.csv' extension"
    else: 
        result["args"]["inputFile"] = args["inputFile"]
    if args["outputFile"] is None:
        if not result["args"]["inputFile"] in ReturnCodes:
            args["outputFile"] = re.sub(".csv$", ".xlsx", args["inputFile"])
        else:
            result["args"]["outputFile"] = ReturnCodes.ERROR
            result["errorMessages"]["outputFile"] = "Error, Unable to generate name of output file due to a invalid input file!"
    else:
        result["args"]["outputFile"] = args["outputFile"]

    return result

def extractMergeArgs(pArgs: argparse.Namespace | None = None) -> dict | None:
    """Return dictionary structure:
    {
        "ReturnCode": (ReturnCode),
        "args": {
            (Argname): (Value or ReturnCode)        
        },
        "errorMessages": { (if needed)
            (Argname): (Error message)
        }    
    }
    """
    args = vars(pArgs)
    if pArgs is None:
        result["ReturnCode"] = ReturnCodes.NO_ARGS_GIVEN
        return result
    result = extractCommonArgs(pArgs)

    #TODO: add autocompile support
    # result["args"]["compileCSV"] = args["compileCSV"]
    result["args"]["compileCSV"] = False

    if not os.path.exists(args["oldFile"]):
        result["ReturnCode"] = ReturnCodes.ERROR
        result["args"]["oldFile"] = ReturnCodes.INVALID_INPUT_FILE_PATH
        result["errorMessages"]["oldFile"] = "Given input file for old data does not exist!"
    elif not str(args["oldFile"]).endswith(".xlsx") and result["args"]["compileCSV"]:
        #TODO: add autocompile support
        ...
    elif not str(args["oldFile"]).endswith(".xlsx") and not result["args"]["compileCSV"]:
        result["ReturnCode"] = ReturnCodes.ERROR
        result["args"]["oldFile"] = ReturnCodes.INVALID_INPUT_FILE_FORMAT
        result["errorMessages"]["oldFile"] = "Given input file for old data is in the wrong format! Please give a file with the .xlsx or, if autocompile is enabled, .csv extension."
    else:
        result["args"]["oldFile"] = args["oldFile"]

    if not os.path.exists(args["newFile"]):
        result["ReturnCode"] = ReturnCodes.ERROR
        result["args"]["newFile"] = ReturnCodes.INVALID_INPUT_FILE_PATH
        result["errorMessages"]["newFile"] = "Given input file for new data does not exist!"
    elif not str(args["newFile"]).endswith(".xlsx") and result["args"]["compileCSV"]:
        #TODO: add autocompile support
        ...
    elif not str(args["newFile"]).endswith(".xlsx") and not result["args"]["compileCSV"]:
        result["ReturnCode"] = ReturnCodes.ERROR
        result["args"]["newFile"] = ReturnCodes.INVALID_INPUT_FILE_FORMAT
        result["errorMessages"]["newFile"] = "Given input file for new data is in the wrong format! Please give a file with the .xlsx or, if autocompile is enabled, .csv extension."
    else:
        result["args"]["newFile"] = args["newFile"]

    if args["mergedFile"] is None:
        if not result["args"]["oldFile"] in ReturnCodes and not result["args"]["newFile"] in ReturnCodes:
            result["args"]["mergedFile"] = f"{result["args"]["oldFile"].removesuffix(".xlsx")}-{result["args"]["newFile"].split("\\")[-1].removesuffix(".xlsx")}_merged.xlsx"
        else:
            result["args"]["mergedFile"] = ReturnCodes.ERROR
            result["errorMessages"]["mergedFile"] = "Error, Unable to generate name of merged file due to invalid input files!"
    else:
        result["args"]["mergedFile"] = args["mergedFile"]

    return result

# Will later be replaced or changed
def showCompileHelp() -> None:
    #TODO: add option for enabling/disabling converting device overview links and user email links
    print("CompileComplianceList.py\n\n" +
          "Arguments:\n"+
          "'-i'/'--InputFile' \t\t- The path of the input file to process. Must be a .csv file (Mandatory)\n" +
          "'-o'/'--OutputFile' \t\t- The path of the output file. If not set, the name of the input file will be used instead\n" +
          "'-w'/'--WantedOS' \t\t- The OS you want to compile the data for. Default is 'Windows'\n" +
          "'-d'/'--DeviceLinkSkip' \t- Skip the creation of the device overview links\n" +
          "'-e'/'--EmailLinks' \t\t- Convert Emails into teams chat links\n" +
          "'-k'/'--KeepDeviceIds' \t\t- Keep the Device Id column\n" +
          "'-h'/'--Help' \t\t\t- Show this help and exit the program\n")

def showMergeHelp() -> None:
    print("CompileComplianceList.py\n\n" +
          "Arguments:\n"+
          "'-o'/'--OldFile' \t\t- The path of the input file of the old data to merge. Must be a .xlsx file (Mandatory)\n" +
          "'-n'/'--NewFile' \t\t- The path of the input file of the new data to merge. Must be a .xlsx file (Mandatory)\n" +
          "'-m'/'--MergedFile' \t\t- The path of the output file. If not set, the name will be generated by this pattern: \n" +
          "\t\t\t\t  '[old file name (with path)]-[new file name (without path)]_merged.xlsx'\n" +
          "'-w'/'--WantedOS' \t\t- [Not yet implemented] The OS you want to merge the data for. Default is 'Windows'\n" +
          "'-c'/'--CompileCSV' \t- [Not yet implemented] Try to automatically compile .csv files if given as input\n" +
          "'-d'/'--DeviceLinkSkip' \t- Skip the creation of the device overview links\n" +
          "'-e'/'--EmailLinks' \t\t- Convert Email into teams chat links\n" +
          "'-k'/'--keepDeviceIds' \t\t- Keep the Device Id column\n" +
          "'-h'/'--Help' \t\t\t- Show this help and exit the program\n")