from enum import Enum

class ReturnCodes(Enum):
    WARNING = 1
    SUCCESS = 0
    PARTIAL_SUCCESS = -9
    ERROR = -1
    NO_ARGS_GIVEN = -2
    INVALID_ARGS = -3
    INVALID_INPUT_FILE = -4
    INVALID_INPUT_FILE_FORMAT = -5
    MISSING_INPUT_FILE = -6
    INVALID_INPUT_FILE_PATH = -7
    MISSING_ARGS = -8
    NEEDS_COMPILE_INPUT_FILES = -9
    INPUT_FILE_COMPILE_FAILED = -10
    INPUT_FILE_COMPILE_PARTIALLY_FAILED = -11
    FUNCTION_NOT_FOR_CURRENT_MODE = -12
    IS_NOT_A_FUNCTION = -13
    COMPLIANCE_LIST_INVALID_OS = -20